CREATE DATABASE [Logging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Logging', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Logging.mdf' , SIZE = 4096KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Logging_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Logging_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Logging] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [Logging] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Logging] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Logging] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Logging] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Logging] SET ARITHABORT OFF 
GO
ALTER DATABASE [Logging] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Logging] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Logging] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Logging] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Logging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Logging] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Logging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Logging] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Logging] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Logging] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Logging] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Logging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Logging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Logging] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Logging] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Logging] SET  READ_WRITE 
GO
ALTER DATABASE [Logging] SET RECOVERY FULL 
GO
ALTER DATABASE [Logging] SET  MULTI_USER 
GO
ALTER DATABASE [Logging] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Logging] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Logging]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Logging] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

/****** Object:  Table [dbo].[Log]    Script Date: 24-5-2013 22:30:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Log](
	[Id] [uniqueidentifier] NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Thread] [nvarchar](255) NOT NULL,
	[Level] [nvarchar](50) NOT NULL,
	[Host] [nvarchar](50) NOT NULL,
	[Logger] [nvarchar](255) NOT NULL,
	[Message] [nvarchar](2000) NOT NULL,
	[Details] [nvarchar](4000) NULL,
	[Exception] [nvarchar](2000) NULL,
	[StackTrace] [nvarchar](4000) NOT NULL,
 CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Log] ADD  CONSTRAINT [DF_Log_Id]  DEFAULT (newsequentialid()) FOR [Id]
GO


